apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: container1
    image: kubetm/init
    volumeMounts:
    - name: test-dir
      mountPath: /test1
  - name: container2
    image: kubetm/init
    volumeMounts:
    - name: test-dir
      mountPath: /test2
  volumes:
  - name: test-dir
    emptyDir: {}