apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  nodeSelector:
    kubernetes.io/hostname: worker-1
  containers: 
  - name: container
    image: kubetm/init
    volumeMounts:
    - name: test-volume
      mountPath: /test1
  volumes:
  - name: test-volume
    hostPath: 
      path: /home/student40
      type: DirectoryOrCreate