apiVersion: v1
kind: PersistentVolume
metadata:
  name: student40-pv
spec: 
  capacity: 
    storage: 2Gi
  accessModes: 
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: student40-sc
  local:
    path: /home/student40
  nodeAffinity: 
    required: 
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker-5