apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
spec: 
  capacity: 
    storage: 5Gi
  accessModes: 
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: local-storage
  local:
    path: /home/student40
  nodeAffinity: 
    required: 
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker-5